# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "starter-new-geon"
client_id = "b9c4b0a063f5b9a14636d1ed024d3710"
application_url = "https://mb-cry-agencies-touched.trycloudflare.com"
web_directories = [ "server", "client" ]
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://mb-cry-agencies-touched.trycloudflare.com/auth/callback",
  "https://mb-cry-agencies-touched.trycloudflare.com/auth/shopify/callback",
  "https://mb-cry-agencies-touched.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "storetools-beta.myshopify.com"
